### ISSUE TITLE
Enabling TPM on U-Boot

### ISSUE THREAD

**Issue by danie007** [WinSystems/meta-winsys#1]
Hi,

We would like to enable TPM on [ITX-P-C444](https://www.winsystems.com/product/itx-p-c444/#tab-specific) board and we using [5.4.24](https://github.com/WinSystems/meta-winsys/tree/itx-p-c444_5.4.24) branch code.

We're following [this guide](https://github.com/joholl/rpi4-uboot-tpm#building-u-boot) to enable **TPM on U-Boot**, however couldn't find the configurations on Winsystems build.

### Can someone help us in getting the TPM working on the board with U-Boot and Linux?

Any help would be much appreciated.

---

CC @tkmozhi

**Comment by bitglitcher** [comment]
Issue too old. Closing.
